INSERT INTO STUDENTS VALUES (101, 'xyz', 'java');
INSERT INTO STUDENTS VALUES (102, 'test2', 'ai');
INSERT INTO STUDENTS VALUES (103, 'test3', 'php');
INSERT INTO STUDENTS VALUES (104, 'abc', 'java');